version: '3'

services:
    app-business-unit:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: app-business-unit
        restart: unless-stopped
        volumes:
            - ./:/usr/scr/app
            - app_business_unit_node_modules:/usr/src/app/node_modules
        ports:
            - 8083:80

volumes:
    app_business_unit_node_modules:
