name: Production

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get npm package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to BFI Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/nbspi/business-unit:${{ steps.package-version.outputs.current-version }}, ghcr.io/nbspi/business-unit:latest

  deployment:
    runs-on: ubuntu-latest
    needs: publish
    environment: production
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.DEVOPS_USER }}
          key: ${{ secrets.DEVOPS_KEY }}
          port: 22
          script: |
            cd ${{ secrets.PROD_DIR }}/business-unit 
            cat token.txt | docker login -u ${{ github.actor }} --password-stdin ghcr.io
            docker compose pull app
            docker compose up -d --build --force-recreate app
            docker image prune -f
